# Generated by Django 3.1.13 on 2021-08-10 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=55, unique=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='title')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('publish_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='publication start')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp_sample.blog', verbose_name='Related blog')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publish_start'],
            },
        ),
    ]
